// src/components/blog/prose.tsx
import { clsx } from "clsx";
import { type JSX, splitProps } from "solid-js";

export function h1(props: JSX.HTMLAttributes<HTMLHeadingElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <h1
      {...others}
      class={clsx(
        "mb-12px mt-12px text-1.875rem font-600 leading-[1.15] tracking-[-.021em] first:mt-0 last:mb-0",
        locals.class,
      )}
    >
      {locals.children}
    </h1>
  );
}

export function h2(props: JSX.HTMLAttributes<HTMLHeadingElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <h2
      {...others}
      class={clsx(
        "my-8 text-2xl font-600 leading-[1.7] tracking-[-.02em]",
        locals.class,
      )}
    >
      {locals.children}
    </h2>
  );
}

export function h3(props: JSX.HTMLAttributes<HTMLHeadingElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <h3
      {...others}
      class={clsx(
        "my-8 text-1.375rem font-600 leading-[1.7] tracking-[-.018em]",
        locals.class,
      )}
    >
      {locals.children}
    </h3>
  );
}

export function h4(props: JSX.HTMLAttributes<HTMLHeadingElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <h4
      {...others}
      class={clsx(
        "my-3 text-1.125rem font-600 leading-[1.7] tracking-[-.014em]",
        locals.class,
      )}
    >
      {locals.children}
    </h4>
  );
}

export function h5(props: JSX.HTMLAttributes<HTMLHeadingElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <h5
      {...others}
      class={clsx(
        "my-3 text-.875rem font-medium leading-[1.7] tracking-[-.006em]",
        locals.class,
      )}
    >
      {locals.children}
    </h5>
  );
}

export function h6(props: JSX.HTMLAttributes<HTMLHeadingElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <h6
      {...others}
      class={clsx(
        "my-3 text-.875rem font-medium leading-[1.7] tracking-[-.006em]",
        locals.class,
      )}
    >
      {locals.children}
    </h6>
  );
}

export function p(props: JSX.HTMLAttributes<HTMLParagraphElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <p {...others} class={clsx("my-5 leading-[1.7]", locals.class)}>
      {locals.children}
    </p>
  );
}

export function a(props: JSX.HTMLAttributes<HTMLAnchorElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <a
      {...others}
      class={clsx("cursor-pointer underline hover:text-slate-9", locals.class)}
    >
      {locals.children}
    </a>
  );
}

export function blockquote(props: JSX.HTMLAttributes<HTMLQuoteElement>) {
  const [locals, others] = splitProps(props, ["class", "children"]);
  return (
    <blockquote {...others} class={clsx("my-6 border-l-4 pl-4", locals.class)}>
      {locals.children}
    </blockquote>
  );
}

// src/components/prose.tsx
import clsx from "clsx";
import { forwardRef, type HTMLAttributes } from "preact/compat";

import { get } from "~/misc/get";

export function h1({ children, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return (
    <h1
      {...props}
      class={clsx(
        "text-1.875rem mt-12px mb-12px font-600 leading-[1.15] tracking-[-.021em] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </h1>
  );
}

export const h2 = forwardRef<
  HTMLHeadingElement,
  HTMLAttributes<HTMLHeadingElement>
>(function h2({ children, ...props }, ref) {
  return (
    <h2
      ref={ref}
      {...props}
      class={clsx(
        "text-1.625rem mt-12px mb-12px font-600 leading-[1.22] tracking-[-.02em] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </h2>
  );
});

export function h3({ children, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return (
    <h3
      {...props}
      class={clsx(
        "text-1.375rem mt-12px mb-12px font-600 leading-[1.25] tracking-[-.018em] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </h3>
  );
}

export function h4({ children, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return (
    <h4
      {...props}
      class={clsx(
        "text-1.125rem mt-8px mb-8px font-600 leading-[1.35] tracking-[-.014em] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </h4>
  );
}

export function h5({ children, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return (
    <h5
      {...props}
      class={clsx(
        "text-.875rem mt-8px mb-8px font-500 leading-[1.4] tracking-[-.006em] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </h5>
  );
}

export function h6({ children, ...props }: HTMLAttributes<HTMLHeadingElement>) {
  return (
    <h6
      {...props}
      class={clsx(
        "text-.875rem mt-8px mb-8px font-500 leading-[1.4] tracking-[-.006em] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </h6>
  );
}

export function p({
  children,
  ...props
}: HTMLAttributes<HTMLParagraphElement>) {
  return (
    <p
      {...props}
      class={clsx(
        "mt-8px mb-8px leading-[1.5] first:mt-0 last:mb-0",
        get(props.class),
      )}
    >
      {children}
    </p>
  );
}

export function a({ children, ...props }: HTMLAttributes<HTMLAnchorElement>) {
  return (
    <a
      {...props}
      class="cursor-pointer text-orange-5 hover:text-orange-7 hover:underline"
    >
      {children}
    </a>
  );
}

export function blockquote({
  children,
  ...props
}: HTMLAttributes<HTMLQuoteElement>) {
  return (
    <blockquote {...props} class="my-2 border-l-4 pl-4">
      {children}
    </blockquote>
  );
}
