// src/layouts/rest-api/category/Expand.solid.tsx
/* @jsxImportSource solid-js */

import { clsx } from "clsx";
import { type JSX, Show } from "solid-js";
import { useExpand } from "~/state/rest-api/expand-section";

export interface ExpandProps {
  section: string;
  title?: string;
  class?: string;
  initialExpand?: boolean;
  children?: JSX.Element;
}
export default function Expand(props: ExpandProps) {
  const { expand, onToggle } = useExpand(
    props.section,
    props.initialExpand ?? false,
  );

  const expandButton = () => (
    <ExpandButton
      title={props.title}
      expand={expand()}
      onClick={() => {
        onToggle(!expand());
        if (!expand()) {
          const heading = document.querySelector(`section#${props.section} h2`);
          heading?.scrollIntoView({ behavior: "smooth" });
        }
      }}
    />
  );
  return (
    <div class={clsx("flex flex-col gap-20", props.class)}>
      <Show when={expand()}>
        {expandButton()}
        {props.children}
      </Show>
      {expandButton()}
    </div>
  );
}

interface ExpandButtonProps {
  title: string | undefined;
  expand: boolean | undefined;
  onClick: () => void;
}
function ExpandButton(props: ExpandButtonProps) {
  return (
    <button type="button" class="relative w-full" onClick={props.onClick}>
      <hr class="absolute top-1/2 z-0 w-full" />
      <div
        class={clsx(
          props.expand ? "bg-slate-7 text-white" : "bg-white",
          "z-1 border-slate-3 relative inline-flex justify-center gap-2 rounded-full border py-2 pl-6 pr-4",
        )}
      >
        <Show
          when={props.expand}
          fallback={
            <>
              <span>{props.title ? `${props.title} 펼치기` : "펼치기"}</span>
              <i class="i-ic-baseline-keyboard-arrow-down text-2xl" />
            </>
          }
        >
          <>
            <span>{props.title ? `${props.title} 접기` : "접기"}</span>
            <i class="i-ic-baseline-keyboard-arrow-up text-2xl" />
          </>
        </Show>
      </div>
    </button>
  );
}

// src/layouts/rest-api/category/Expand.tsx
import type React from "preact/compat";

export interface ExpandProps {
  title?: string;
  className?: string;
  children?: React.ReactNode;
  expand?: boolean;
  onToggle?: (expand: boolean) => void;
  onCollapse?: () => void;
}
export default function Expand({
  title = "",
  className = "",
  children,
  expand,
  onToggle,
  onCollapse,
}: ExpandProps) {
  const expandButton = (
    <ExpandButton
      title={title}
      expand={expand}
      onClick={() => {
        onToggle?.(!expand);
        if (expand) onCollapse?.();
      }}
    />
  );
  return (
    <div class={`flex flex-col gap-20 ${className}`}>
      {expand && expandButton}
      {expand && children}
      {expandButton}
    </div>
  );
}

interface ExpandButtonProps {
  title: string;
  expand?: boolean | undefined;
  onClick?: () => void;
}
function ExpandButton({ title, expand, onClick }: ExpandButtonProps) {
  return (
    <button class="relative w-full" onClick={onClick}>
      <hr class="absolute top-1/2 w-full" />
      <div
        class={`${
          expand ? "bg-slate-7 text-white" : "bg-white"
        } border-slate-3 relative inline-flex justify-center gap-2 rounded-full border py-2 pl-6 pr-4`}
      >
        {expand ? (
          <>
            <span>{title ? `${title} 접기` : "접기"}</span>
            <i class="i-ic-baseline-keyboard-arrow-up text-2xl" />
          </>
        ) : (
          <>
            <span>{title ? `${title} 펼치기` : "펼치기"}</span>
            <i class="i-ic-baseline-keyboard-arrow-down text-2xl" />
          </>
        )}
      </div>
    </button>
  );
}
