// src/layouts/rest-api/DescriptionArea.tsx
import { useEffect, useRef, useState } from "preact/hooks";

export interface DescriptionAreaProps {
  maxHeightPx?: number;
  bgColor?: string;
  children: any;
}
export default function DescriptionArea({
  maxHeightPx = 16 * 12, // 12rem
  bgColor = "white",
  children,
}: DescriptionAreaProps) {
  const childrenContainerRef = useRef<HTMLDivElement>(null);
  const [maxHeightIsSmall, setMaxHeightIsSmall] = useState(false);
  const [open, setOpen] = useState(false);
  const maxHeight = open ? "" : `${maxHeightPx / 16}rem`;
  useEffect(() => {
    function checkMaxHeightIsSmall() {
      const rect = childrenContainerRef.current?.getBoundingClientRect();
      const maxHeightIsSmall = (rect?.height || 0) > maxHeightPx;
      setMaxHeightIsSmall(maxHeightIsSmall);
    }
    checkMaxHeightIsSmall();
    addEventListener("resize", checkMaxHeightIsSmall);
    return () => removeEventListener("resize", checkMaxHeightIsSmall);
  }, [maxHeightPx]);
  return (
    <div class="relative overflow-hidden" style={{ maxHeight }}>
      <div class="flex flex-col gap-2" ref={childrenContainerRef}>
        {children}
      </div>
      {maxHeightIsSmall && !open && (
        <>
          <div
            class="pointer-events-none absolute left-0 top-0 h-full w-full"
            style={{
              background: `linear-gradient(to bottom, transparent 50%, ${bgColor})`,
            }}
          />
          <button
            class="h-2rem absolute bottom-0 flex w-full items-center justify-center text-sm font-bold"
            onClick={() => setOpen(true)}
          >
            <div class="overflow-hidden rounded-full px-4 py-2 backdrop-blur-sm">
              자세히...
            </div>
          </button>
        </>
      )}
    </div>
  );
}

// src/layouts/rest-api/DescriptionArea.solid.tsx
/* @jsxImportSource solid-js */

import {
  mergeProps,
  type JSX,
  createSignal,
  createMemo,
  createEffect,
  Show,
} from "solid-js";
import { createElementSize } from "@solid-primitives/resize-observer";

export interface DescriptionAreaProps {
  maxHeightPx?: number;
  bgColor?: string;
  children: JSX.Element;
}
export default function DescriptionArea(_props: DescriptionAreaProps) {
  const props = mergeProps(_props, {
    maxHeightPx: 16 * 12,
    bgColor: "white",
  });

  const [childrenContainer, setChildrenContainer] =
    createSignal<HTMLDivElement | null>(null);
  const [maxHeightIsSmall, setMaxHeightIsSmall] = createSignal(false);
  const [isOpen, setIsOpen] = createSignal(false);
  const maxHeight = createMemo(() =>
    isOpen() ? "" : `${props.maxHeightPx / 16}rem`,
  );

  const containerSize = createElementSize(childrenContainer);
  createEffect(() => {
    const maxHeightIsSmall = (containerSize?.height || 0) > props.maxHeightPx;
    setMaxHeightIsSmall(maxHeightIsSmall);
  });

  return (
    <div class="relative overflow-hidden" style={{ "max-height": maxHeight() }}>
      <div class="flex flex-col gap-2" ref={setChildrenContainer}>
        {props.children}
      </div>
      <Show when={maxHeightIsSmall() && !isOpen()}>
        <div
          class="pointer-events-none absolute left-0 top-0 h-full w-full"
          style={{
            background: `linear-gradient(to bottom, transparent 50%, ${props.bgColor})`,
          }}
        />
        <button
          type="button"
          class="h-2rem absolute bottom-0 flex w-full items-center justify-center text-sm font-bold"
          onClick={() => setIsOpen(true)}
        >
          <div class="overflow-hidden rounded-full px-4 py-2 backdrop-blur-sm">
            자세히...
          </div>
        </button>
      </Show>
    </div>
  );
}
